services:
  mysql-db-inventory:
    image: mariadb:10.6
    container_name: mysql-db-inventory
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: inventory-db
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9999:80
    environment:
      PMA_HOST: mysql-db-inventory
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    ports:
      - '8092:8092'
    expose:
      - '8092'
    restart: always
    depends_on:
      mysql-db-inventory:
        condition: service_healthy
    environment:
      - DB_URL=jdbc:mysql://mysql-db-inventory:3306/inventory-db

volumes:
  mysql_data: